/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import javax.swing.*;

/**
 *
 * @author SYAFIQ
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnMaster = new javax.swing.JMenu();
        mnItKelas = new javax.swing.JMenuItem();
        mnItSiswa = new javax.swing.JMenuItem();
        mnItStaffTU = new javax.swing.JMenuItem();
        mnAccount = new javax.swing.JMenu();
        mnItLogout = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        mnMaster.setText("Master");

        mnItKelas.setText("Kelas");
        mnItKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItKelasActionPerformed(evt);
            }
        });
        mnMaster.add(mnItKelas);

        mnItSiswa.setText("Siswa");
        mnItSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItSiswaActionPerformed(evt);
            }
        });
        mnMaster.add(mnItSiswa);

        mnItStaffTU.setText("Staff TU");
        mnItStaffTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItStaffTUActionPerformed(evt);
            }
        });
        mnMaster.add(mnItStaffTU);

        jMenuBar2.add(mnMaster);

        mnAccount.setText("Account");

        mnItLogout.setText("Logout");
        mnItLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItLogoutActionPerformed(evt);
            }
        });
        mnAccount.add(mnItLogout);

        jMenuBar2.add(mnAccount);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DBConnection.username = "";
        new LoginAdmin().setVisible(true);
    }//GEN-LAST:event_mnItLogoutActionPerformed

    private void mnItKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItKelasActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        AdminKelas kelas = new AdminKelas();
        jDesktopPane1.add(kelas);
        kelas.setVisible(true);
    }//GEN-LAST:event_mnItKelasActionPerformed

    private void mnItSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItSiswaActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        AdminSiswa siswa = new AdminSiswa();
        jDesktopPane1.add(siswa);
        siswa.setVisible(true);
    }//GEN-LAST:event_mnItSiswaActionPerformed

    private void mnItStaffTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItStaffTUActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        AdminStaffTU staffTU = new AdminStaffTU();
        jDesktopPane1.add(staffTU);
        staffTU.setVisible(true);
    }//GEN-LAST:event_mnItStaffTUActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mnAccount;
    private javax.swing.JMenuItem mnItKelas;
    private javax.swing.JMenuItem mnItLogout;
    private javax.swing.JMenuItem mnItSiswa;
    private javax.swing.JMenuItem mnItStaffTU;
    private javax.swing.JMenu mnMaster;
    // End of variables declaration//GEN-END:variables
}
